"""
Django settings for websitethree project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

load_dotenv(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

# Localhost, EC2 IP, and domain name.
ALLOWED_HOSTS = ['127.0.0.1', '54.177.68.114', 'jorgeramirez.net', 'www.jorgeramirez.net']


# Application definition

INSTALLED_APPS = [
    'daphne',                                   # Daphne is what actually runs your Django project for async features, like real-time channels. Daphne systemd Service is what we used for production. (Read the README.md for "chat_api" for more information).
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",                              # django-cors-headers package. This application injects the required HTTP headers into our responses, allowing frontend applications running on other domains (like React, Vue, or Angular) to interact with our Django backend.
    'rest_framework',                           
    'resume_analyzer_app_api',                  
    "rest_framework_simplejwt.token_blacklist", # [https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html] - Comes installed with Djangos simplejwt app. Make sure to run python manage.py migrate to run the app’s migrations.
    "ragspace_api",                                        
    "channels",                                 # Used for chat_api websocket management. (Is an official project that extends Django to handle WebSockets and other real-time protocols) - Installed in requirements.txt.
    "chat_api"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'websitethree.urls'              # Simply says our Root URL config is the file sitting at websitethree/websitethree/urls.py.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR,
            # os.path.join(BASE_DIR, 'homepage-frontend/build'),
            # os.path.join(BASE_DIR, 'homepage-react-frontend-parallax-semantic/build'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'websitethree.wsgi.application'     
ASGI_APPLICATION = "websitethree.asgi.application"      # Replaces WSGI to allow asynchronous and traditional synchronous Python applications. (Needed for Relay)(Allows normal http traffic aswell).

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {                                           # Basic MySQL database connection configuration using environment variable for confidential information.
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "resume_analyzer_app_api",
        "USER": "django",
        "PASSWORD": os.getenv("MYSQL_PASSWORD"),
        "HOST": "localhost",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Tell Django to Use Our Custom Model for Authentication. We are telling Django to bypass its default built-in user model and instead use the User class defined inside the models file of our resume_analyzer_app_api application.
AUTH_USER_MODEL = "resume_analyzer_app_api.User"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "/website-folder/site/public/static"
MEDIA_ROOT= "/website-folder/site/public/media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'homepage-frontend/build/static'),
    os.path.join(BASE_DIR, 'homepage-react-frontend-parallax-semantic/build/static'),
    os.path.join(BASE_DIR, 'resume-analyzer-app/dist'),
    os.path.join(BASE_DIR, 'ragspace-frontend/dist'),
    os.path.join(BASE_DIR, 'chat-frontend/dist'),
]

REST_FRAMEWORK = { 
    "DEFAULT_AUTHENTICATION_CLASSES": ( 
        "rest_framework_simplejwt.authentication.JWTAuthentication", 
    ), 

    "DEFAULT_PERMISSION_CLASSES": ( 
        "rest_framework.permissions.IsAuthenticated", 
    ), 
}

from datetime import timedelta 
SIMPLE_JWT = { 
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15), 
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), 

    "ROTATE_REFRESH_TOKENS": True, 
    "BLACKLIST_AFTER_ROTATION": True, 

    "UPDATE_LAST_LOGIN": True, 
}

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000"
]

# Instead of sending an actual email, Django prints the email contents into your development terminal. This is perfect for testing / development.
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "noreply@jorgeramirez.net"

FRONTEND_URL = os.getenv(
    "FRONTEND_URL"
)



# Amazon SES Email Connection Settings
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv(
    "EMAIL_HOST"
)
EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        587
    )
)
EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER"
)
EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD"
)
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL"
)



# S3 Config for ResuScan
AWS_STORAGE_BUCKET_NAME = os.getenv(
    "AWS_STORAGE_BUCKET_NAME"
)

AWS_S3_REGION_NAME = os.getenv(
    "AWS_S3_REGION_NAME",
    "us-west-1",
)

AWS_S3_UPLOAD_PREFIX = os.getenv(
    "AWS_S3_UPLOAD_PREFIX",
    "resumes",
)




RESUME_MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB

RESUME_ALLOWED_CONTENT_TYPES = {
    "application/pdf": ".pdf", # pdf file type
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx", # docx file type
}

RESUME_UPLOAD_URL_EXPIRATION = 300  # 5 minutes




OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY"
)

OPENAI_RESUME_MODEL = os.getenv(
    "OPENAI_RESUME_MODEL",
    "gpt-5-mini",
)


# S3 Config for Ragspace.
RAGSPACE_AWS_ACCESS_KEY_ID = os.getenv("RAGSPACE_AWS_ACCESS_KEY_ID")
RAGSPACE_AWS_SECRET_ACCESS_KEY = os.getenv("RAGSPACE_AWS_SECRET_ACCESS_KEY")
RAGSPACE_AWS_STORAGE_BUCKET_NAME = os.getenv("RAGSPACE_AWS_STORAGE_BUCKET_NAME")
RAGSPACE_AWS_REGION = os.getenv("RAGSPACE_AWS_REGION")


RAG_CHUNK_SIZE = 600
RAG_CHUNK_OVERLAP = 120
RAG_CANDIDATE_K = 12
RAG_FINAL_K = 5
RAG_SCORE_THRESHOLD = 0.30


RAG_EMBEDDING_MODEL = "text-embedding-3-small" # OpenAI Embedding Model For RAGspace.


# Qdrant config for Ragspace.
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")

RAG_QDRANT_COLLECTION = "ragspace_chunks"
RAG_EMBEDDING_DIMENSIONS = 1536


# Voyage API config for Ragspace.
VOYAGE_API_KEY = os.getenv("VOYAGE_API_KEY")

RAG_RERANKING_ENABLED = False
RAG_RERANK_MODEL = "rerank-2.5-lite"

RAG_GENERATION_MODEL = "gpt-5-mini"

RAG_CONTEXTUALIZATION_MODEL = "gpt-5-mini"
RAG_HISTORY_MESSAGE_LIMIT = 8




# Channels config for Relay.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

