# Generated by Django 6.0.7 on 2026-08-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_app_api', '0003_resume_resumeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending_upload', 'Pending Upload'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending_upload', max_length=30),
        ),
    ]
