# Generated by Django 6.0.7 on 2026-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_app_api', '0004_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='thumbnail_s3_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
