# Generated by Django 6.0.7 on 2026-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragspace_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
